version: '3'
services:

  dev-container:
    build:
      context: ./docker
      dockerfile: LocalDevelopDockerfile
    container_name: dev-container
    ports:
      - 3000:3000
      - 8080:8080
    tty: true # コンテナの起動永続化
    volumes:
      - .:/usr/src/app
